### ISSUE TITLE
read-only dynamic object form elements (JSON-variables) get scrambled after form submit

### ISSUE THREAD

**Issue by hloydl** [it-at-m/digiwf-json-serialization#7]
**Describe the bug**
After I submit a form with **read-only** dynamic object form elements (Camunda JSON-variables), these variables appear "scrambled", the JSON key-values are completely reset to some kind of random key-values. 

**To Reproduce**
1. create a Camunda process with 1) script or expression to initialize a json-process variable b) user task bound to a form to display this json-variable (read-only) through a dynamic object element 
2. start the Camunda process
3. Submit the form
4. check the json-variable in (history) view in camunda cockpit

**Expected behavior**
The json variable should be unchanged (as initialized)

**Screenshots**
![image](https://user-images.githubusercontent.com/7716757/158158890-cee7940d-581c-4be8-9260-6b79067f4b01.png)
Example json as initialized:
`lizenzdaten: {"dauer":"12 Monate","gebuehr":6000,"name":"Klinikviertel","nummer":123}`

After form submit: 
`lizenzdaten: {"number":false,"boolean":false,"null":false,"string":false,"array":false,"dataFormatName":"application/json","nodeType":"OBJECT","value":false,"object":true}`

**Additional context**
all json-variables (form: dynamic object read-only) get this value.

**Comment by dominikhorn93** [comment]
@hloydl could you add the form config please? (download an upload here)

**Comment by hloydl** [comment]
[Formular-Parkausweis Berechtigung prüfen.txt](https://github.com/it-at-m/digiwf-json-serialization/files/8244199/Formular-Parkausweis.Berechtigung.prufen.txt)

Had to rename it to *.txt to upload it here. 
In the attached form config ONLY lizenzdaten ist set to read-only!

`"lizenzdaten": {
              "key": "lizenzdaten",
              "fieldType": "object",
              "title": "Lizenzdaten",
              "type": "object",
              "description": "Lizenzdaten",
              "readOnly": true,
              "x-options": {
                "fieldColProps": { "cols": 12, "sm": 12, "messages": {} }
              },
              "x-props": { "outlined": true, "dense": true },
              "x-rules": [],
              "properties": {
                "dauer": {
                  "fieldType": "select",
                  "title": "Dauer",
                  "type": "string",
                  "key": "dauer",
                  "readOnly": true,    ....    `

**Comment by dominikhorn93** [comment]
Fixed with Release 0.0.5 -> Merger Request is already created for our internal project.
I guess it will be available in test stages on monday.
